aws/sagemaker-mxnet-training-toolkit

src/mxnet_container/train.py

Remove reference to dns

---

docker/1.2.1/final/Dockerfile.cpu
docker/1.2.1/final/Dockerfile.gpu
test/integ/test_linear_regression.py
test/resources/linear_regression/linear_regression.py

* Add Dockerfiles for 1.2.1
* Fix integ tests for py2.

Add Dockerfiles for 1.2.1

---

docker/1.2.1/final/Dockerfile.cpu
docker/1.2.1/final/Dockerfile.gpu

Install onnx in 1.2.1 containers

---

src/mxnet_container/train.py

pending https://github.com/aws/sagemaker-python-sdk/pull/390
This change adds a warning to the beginning of every training job about the upcoming script mode changes.

Add warning about upcoming training script format change to training log

---

setup.py

pin requests version to fix conflict in test

pin requests version

---

.flake8
.gitignore
docker/1.3.0/final/Dockerfile.cpu
docker/1.3.0/final/Dockerfile.gpu
setup.py
src/sagemaker_mxnet_container/serving.py
test/integ/local_mode.py
test/integ/test_gluon_hosting.py
test/integ/test_mnist_training.py
test/resources/gluon_hosting/code/gluon.py
test/unit/test_serving.py

I didn't update all of the hosting-related integ tests because of the lack of custom `transform_fn` support in SageMaker Containers (which is my next task). (Also more integ test changes are coming anyway.)

Migrate serving support

---

src/sagemaker_mxnet_container/default_save.py
test/integration/local/test_linear_regression.py
test/resources/linear_regression/linear_regression.py
test/unit/test_default_save.py

Add default save method and update linear regression test

---

README.rst
test/conftest.py
test/integration/local/test_keras_training.py
test/integration/local/test_linear_regression.py
test/integration/local/test_mnist_training.py
test/integration/sagemaker/test_mnist_distributed.py

need to reflect changes from #41
also added some general testing fixes - notably switched back to 'aws-id' to match PyTorch/Chainer (not sure why I switched to match TF in the first place).

Update testing section of the README

---

src/sagemaker_mxnet_container/serving.py
test/unit/test_serving.py

Fix unit test for csv deserialization

---

.gitignore
test/integration/local/test_mnist_training.py
test/resources/mnist/mnist.py

in light of #46, this seemed prudent.

Add integration test for inference with CSV

---

src/sagemaker_mxnet_container/training.py
test/integration/local/test_mnist_training.py
test/integration/sagemaker/test_mnist_distributed.py

Change parameter server hyperparameter name

---

docker/1.3.0/final/Dockerfile.cpu
docker/1.3.0/final/Dockerfile.gpu

add port label to dockerfile

---

src/sagemaker_mxnet_container/serving.py
test/unit/test_serving.py

Elastic Inference support for MXNet.

modify default model fn for Elastic Inference

---

src/sagemaker_mxnet_container/serving.py
test/integration/local/test_default_model_fn.py
test/unit/test_serving.py

fix response content_type handling:
- no accept header
- mimetype and content_type handled correctly

fix response content_type handling

---

docker/1.3.0/final/Dockerfile.cpu
docker/1.3.0/final/Dockerfile.gpu

This is for compatibility with a recent SageMaker Containers change:
https://github.com/aws/sagemaker-containers/pull/157/files#diff-25848f52cb812bb370f854bffb2e7b40

Add python-dev and build-essential to Dockerfiles

---

src/sagemaker_mxnet_container/serving.py
test/unit/test_serving.py

aws/sagemaker-python-sdk#551
I refactored the context retrieval into a separate private method so that the TODO note about not just using the default CPU context didn't need to be copied to multiple places.

Add numpy array support in default serving methods

---

README.rst

Adding section to README in regards to Elastic Inference.

Add EI documentation within README

---

src/sagemaker_mxnet_container/serving.py
test/unit/test_serving.py

Set logging level before importing user module

---

buildspec.yml

Update build spec with PR number. So the remote instance will test on the PR branch.

Update buildspec with PR number

---

buildspec.yml

1. Remove ssh config configuration in buildspec, this is now configured in remote testing script.
2. Change the cpu/gpu test order to be consistent with other frameworks.

Remove ssh configuration in buildspec

---

README.rst

Remove outdated information from README

---

buildspec-release.yml

to match recent changes in the TF release buildspec

fix: adjust parallelism in buildspec-release.yml

---

docker/1.4.1/Dockerfile.cpu
docker/1.4.1/Dockerfile.gpu

**Detail**
Update MXNet to 1.4.1, keep other dependencies as the same(CUDA stack, pip packages etc);
**Test**
Tested in pipeliens.

Add dockerfiles for MXNet 1.4.1

---

buildspec-release.yml

fix: use correct variable name in release buildspec

---

buildspec-release.yml

Made a silly mistake in #96, which broke the build: https://us-west-2.console.aws.amazon.com/codesuite/codebuild/projects/sagemaker-mxnet-container-release/build/sagemaker-mxnet-container-release:92b60e9c-7127-435c-b427-1cc29db14468/log?region=us-west-2. This PR should hopefully fix that.

change: fix local GPU test command in buildspec-release.yml

---

setup.py

change: pin sagemaker in test dependencies

---

setup.py

- Updating SageMaker Containers to the latest version, including code fixes and support for network isolation.

Updating SageMaker Containers to the latest version

---

buildspec-release.yml

the right parenthesis was in the wrong spot in the cp command :(

change: fix copy command in buildspec-release.yml

---

buildspec-release.yml
test/integration/__init__.py

Make the regional tests work for the new regions.

New regions

---

buildspec.yml
tox.ini

Fix flake8 and add flake it to pr build.

change: add flake8 in buildspec.yml and fix flake8

---

buildspec-release.yml

Stop interfering with gpu types.

change: split cpu and gpu test commands.

---

test/integration/__init__.py

change: update instance type region availability

---

.gitignore
buildspec-release.yml
buildspec.yml
docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py2/dockerd-entrypoint.py
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu
docker/1.6.0/py3/dockerd-entrypoint.py
setup.py
src/sagemaker_mxnet_container/deep_learning_container.py
test/conftest.py
test/integration/sagemaker/test_dgl.py
test/integration/sagemaker/test_training.py
test/integration/sagemaker/test_training_smdebug.py
test/resources/dgl_gcn/gcn.py
test/resources/mnist/mnist.py
test/resources/mnist/mnist_gluon_basic_hook_demo.py
test/unit/test_deep_learning_container.py

- new Dockerfiles with MX 1.6.0
- SMDebug, SMExperiments and DGL support
- Added new SageMaker tests

Release 1.6.0 Dockerfiles

---

docker/artifacts/deep_learning_container.py
docker/artifacts/dockerd-entrypoint.py
scripts/build_all.py
scripts/publish_all.py
src/sagemaker_mxnet_container/__init__.py
src/sagemaker_mxnet_container/training.py
src/sagemaker_mxnet_container/training_utils.py
test/__init__.py
test/conftest.py
test/integration/__init__.py
test/integration/local/local_mode_utils.py
test/integration/local/test_mnist_training.py
test/integration/local/test_onnx.py
test/integration/sagemaker/test_dgl.py
test/integration/sagemaker/test_training.py
test/integration/sagemaker/test_training_smdebug.py
test/integration/sagemaker/test_tuning.py
test/integration/sagemaker/timeout.py
test/resources/mnist/mnist.py
test/resources/onnx/code/onnx_export.py
test/unit/test_deep_learning_container.py
test/unit/test_training.py
test/unit/test_training_utils.py

change: update copyright year in license header

---

README.rst

- Update README to use newest framework versions and use new unified build context

Update README for 1.6.0 release

---

README.rst
buildspec.yml

We now would like build context to be in the same directory that the Dockerfiles are in inside this repo. Updating buildspec and README to reflect this.

Build context changes based on new requirements

---

buildspec.yml
docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu

*Description of changes:* Use sagemaker-mxnet-training package from pypi.

change: Use sagemaker-mxnet-training package from pypi.

---

docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu

update: Update license URL

---

docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu
setup.py
test/integration/sagemaker/test_experiments.py

* upgrade to latest version of sagemaker-experiments
* the latest version has minor improvements of adding additional methods of searching for and filtering trial components

upgrade to latest version of sagemaker-experiments

---

docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu

change: install SageMaker Python SDK into Python 3 images

---

setup.py
test/integration/sagemaker/test_experiments.py

install sagemaker-experiments only for python 3.6

install experiments sdk only for python 3.6

---

test/integration/sagemaker/test_experiments.py

move experiments import statements after python version check

move experiments import statements after python version check

---

docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu

Using smdebug built from source. will be replaced with smdebug==0.7.0 once it is released.

Update smdebug to 0.7.0

---

setup.py

install sm experiments on any python version 3.5 or above

install sm experiments on any python version 3.5 or above

---

README.rst

doc: update container build instructions with correct tar file name

---

docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu

Updating smdebug version to the latest

smdebug 0.7.1

---

buildspec.yml

infra: do not run DLC tests when toolkit has changes.

infra: do not run DLC tests when toolkit has changes.

---

test/resources/cv/train_cifar.py

Fix the number of batches in tests when too many gpu is used for training

fix for too many gpus

---

buildspec-toolkit.yml
buildspec.yml

Use tox commands in buildspecs

infra: use tox in buildspecs
