README.rst
Python 3 build were failing due to errors such as
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1743: ordinal not in range(128)
```
due to the use of smart quotes in `README.rst`.
=> Fix quotes so that Python 3 container can be built

src/mxnet_container/train.py
If the user script URI is an S3 URI we will download it, otherwise
we assume that the file is already present in the container. (Local
mode will mount it).
=> Allow the user script to be mounted locally.

src/mxnet_container/__init__.py
To enable wild import, the modules specified in __all__ should be module names(string) instead of modules themselves.
Seems no change log here, so no change for that.
Didn't add any unit tests since wild import cannot be performed within scope of a test function. And adding wild import at top of a test file seems an overkill...
Reference: https://docs.python.org/3/tutorial/modules.html#importing-from-a-package
=> Fix __all__ for wild import

setup.py, src/sagemaker_mxnet_container/distributed.py, src/sagemaker_mxnet_container/training.py, test/integ/test_mnist_training.py, test/resources/mnist/mnist_script_mode.py, test/unit/test_distributed.py
Add a class for users to use to set up a parameter server like before to use with distributed training.
A few note:
* this doesn't work if you have only one host but still want the parameter server. Likely an issue with a process ending before it should, but I'm not sure yet. will investigate further.
* naming is hard. feel free to suggest alternatives :)
=> Add support for distributed training

setup.py, src/sagemaker_mxnet_container/serving.py, test/integ/test_default_model_fn.py, test/integ/test_hosting.py, test/resources/default_handlers/code/empty_module.py, test/unit/test_serving.py
a few different things happened here:
1. thanks to aws/sagemaker-containers#122, detecting a `transform_fn` in the user module doesn't need to throw an error
1. ^that let me unskip one of the integ tests
1. then I realized I could have unskipped one of the integ tests in my last PR
1. also I found some bugs in my previous serving code, so that's fixed here
=> Fix serving, update integ tests, and allow user-supplied transform_fn

test/integration/__init__.py, test/integration/local/test_default_model_fn.py, test/integration/local/test_gluon_hosting.py, test/integration/local/test_hosting.py, test/integration/local/test_mnist_training.py
Not the greatest solution, but this should mitigate the worker timeouts we've seen in only very specific cases.
=> Set number of model workers for inference server

docker/1.3.0/final/Dockerfile.cpu, src/sagemaker_mxnet_container/serving.py, test/unit/test_serving.py
In retrospect, I've decided blindly opening up the permitted content types was a bad idea.
=> Fix inference for CSV and limit valid content types

docker/1.3.0/final/Dockerfile.cpu, docker/1.3.0/final/Dockerfile.gpu
https://github.com/aws/sagemaker-containers/issues/159
1. Add LANG to set language as utf-8
2. Add LC_ALL to set the locale to be utf-8
3. Add PYTHONIOENCODING=UTF-8 for python 2  to encode with utf-8 as default.
Reference:
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING
https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do
=> Add env variable to make sure default encoding is utf-8

docker/1.3.0/final/Dockerfile.cpu, docker/1.3.0/final/Dockerfile.gpu
Freeze pip version <=18.1 to be consistent with other SageMaker framework containers.
=> Freeze pip version to <=18.1

src/sagemaker_mxnet_container/serving.py, test/unit/test_serving.py
MXNet automatically transfers data to the accelerator as necessary, so there's no support for using `mx.eia()` when creating `NDArray`s
https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-mxnet-elastic-inference.html
=> Don't use mx.eia() when allocating memory for NDArrays

README.rst, test/conftest.py, test/integration/__init__.py, test/integration/sagemaker/test_elastic_inference.py
Added EI integ test
Test results:
**=== non-supported region ===**
pytest -rs test/integration/sagemaker/test_elastic_inference.py --accelerator-type ml.eia1.medium --region ap-southeast-1
test/integration/sagemaker/test_elastic_inference.py::test_deploy_elastic_inference_with_pretrained_model SKIPPED
============================================================================== short test summary info ==============================================================================
SKIP [1] /Users/choidan/workspace/container/sagemaker-mxnet-containers/test/integration/sagemaker/test_elastic_inference.py:45: EI is not supported in ap-southeast-1
**=== no accelerator provided ===**
pytest test/integration/sagemaker/test_elastic_inference.py …
=> add elastic inference sagemaker integ test

docker/1.3.0/final/Dockerfile.cpu, docker/1.3.0/final/Dockerfile.gpu, docker/1.3.0/final/keras.json, test/resources/keras/keras_mnist.py
Keras defaults to "channels last" likely because that's what TF expects; MXNet, however, requires "channels first."
Because our containers don't touch the training script itself, using a Keras config file seems like the best option. This file should live in `~/.keras/keras.json`, and I wasn't able to find a way to change that path (setting `KERAS_HOME` did not work despite https://stackoverflow.com/a/46506589). When our containers are run without any user specification (as I don't believe they are in SageMaker), `~` points to `/root`.
When future versions of MXNet are added, it will probably make sense to not house `keras.json` in the version-specific Docker folder. Once we've finished updating our build processes, I think it'll be easiest to revise the …
=> Set 'channels first' for Keras

docker/1.4.0/final/Dockerfile.cpu.training, docker/1.4.0/final/Dockerfile.gpu.training
I've removed some of the arguments that existed in the 1.3.0 Dockerfile.
```
docker build -t 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-training:1.4-gpu-py3 -f docker/1.4.0/final/Dockerfile.gpu.training --build-arg py_version=3 .
Successfully built 7df913bc3179
Successfully tagged 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-training:1.4-gpu-py3
docker build -t 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-training:1.4-cpu-py3 -f docker/1.4.0/final/Dockerfile.cpu.training --build-arg py_version=3 .
Successfully built f5ae39c6228d
Successfully tagged 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-training:1.4-cpu-py3
```
I've added a few TODOs, as names and such are subject to change for the official release.
By submitting this …
=> add training dockerfile for 1.4.0

docker/1.4.0/final/Dockerfile.cpu.serving, docker/1.4.0/final/Dockerfile.gpu.serving
The build arg now requires 3.6 and 2.7 instead of the respective 2 and 3. As the base image we build from has that in the name and doing if statement conditionals within the Dockerfile can't fulfill that purpose.
I've removed some of the arguments that existed in the 1.3.0 Dockerfile.
```
docker build -t 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-serving:1.4-cpu-py3 -f docker/1.4.0/final/Dockerfile.cpu.serving --build-arg py_version=3.6 .
Successfully built 39aff94ef040
Successfully tagged 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-serving:1.4-cpu-py3
docker build -t 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-serving:1.4-gpu-py3 -f docker/1.4.0/final/Dockerfile.gpu.serving --build-arg py_version=3.6 .
Successfully built 810823b4cf77 …
```
=> add serving dockerfile for 1.4.0

docker/1.4.0/final/Dockerfile.eia
The build arg now requires 3.6 and 2.7 instead of the respective 2 and 3. As the base image we build from has that in the name and doing if statement conditionals within the Dockerfile can't fulfill that purpose.
I've removed some of the arguments that existed in the 1.3.0 Dockerfile.
```
docker build -t 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-eia:1.4-cpu-py3 -f docker/1.4.0/final/Dockerfile.eia --build-arg py_version=3.6 .
Successfully built 774af2ffa8d6
Successfully tagged 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-mxnet-eia:1.4-cpu-py3
```
=> add eia dockerfile for 1.4.0

test/unit/test_training_utils.py
The latest version of `mock` changed some behavior, which caused the unit tests to fail.
=> Fix mock_open usage

buildspec-release.yml, test/conftest.py
follows https://github.com/aws/sagemaker-tensorflow-container/pull/208. I looked through the PR buildspec but didn't see an obvious way to incorporate it without just refactoring large parts of it, so I've left that out of this PR.
```
$ pytest test/integration/ --collect-only
======== test session starts ========
[...]
collected 8 items                                                                                                                                                                                                                                                                                                                                                        
<Module test/integration/local/test_keras_training.py>
<Function …
```
=> change: parametrize Python version and processor type in integ tests

setup.py
The recently-adding hyperparameter tuning test (#95) exposed some issue with our dependency chain not having an updated version of botocore.
Similar: https://github.com/aws/sagemaker-tensorflow-container/pull/187
=> change: explicitly set lower bound for botocore version

buildspec-release.yml
the release builds are failing with the error "invalid loads value" on deployments.json ([example CodeBuild job](https://us-west-2.console.aws.amazon.com/codesuite/codebuild/projects/sagemaker-mxnet-container-deploy/build/sagemaker-mxnet-container-deploy:c7920a25-f192-4704-9c36-566a3f3d84c3/log?region=us-west-2))
=> fix: remove JSON syntax error from buildspec-release.yml

scripts/build_all.py
Forgot to change this as part of the 1.4.1 upgrade. Tested in my personal account as much as I could (basically up until the local GPU tests, which don't work in our sandboxed builds at the moment).
=> change: fix build directory in scripts/build_all.py

src/sagemaker_mxnet_container/training.py, test/unit/test_training.py
https://github.com/aws/sagemaker-python-sdk/pull/941
* this change is specifically to take advantage of https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_process.py#L76-L86
* the approach is copied from https://github.com/aws/sagemaker-chainer-container/blob/master/src/sagemaker_chainer_container/training.py (but without the MPI stuff)
=> change: use SageMaker Containers' ProcessRunner for executing the entry point

docker/1.6.0/py2/Dockerfile.cpu, docker/1.6.0/py2/Dockerfile.gpu, docker/1.6.0/py3/Dockerfile.cpu, docker/1.6.0/py3/Dockerfile.gpu
* Constrain setuptools version in py2 dockerfiles
* Pin scipy version to 1.2.2
=> update: Constrain package versions in 1.6.0 dockerfiles

docker/1.6.0/py2/Dockerfile.cpu, docker/1.6.0/py2/Dockerfile.gpu, docker/1.6.0/py3/Dockerfile.cpu, docker/1.6.0/py3/Dockerfile.gpu
The aws-mxnet pip wheels hosted at [aws-mxnet-pypi/1.6.0](https://aws-mxnet-pypi.s3-us-west-2.amazonaws.com/1.6.0) cannot be installed using pip version 20.0.1
Error message:
```
root@db8864b0db13:/# pip install https://aws-mxnet-pypi.s3-us-west-2.amazonaws.com/1.6.0/aws_mxnet_cu101mkl-1.6.0rc0-py2.py3-none-manylinux1_x86_64.whl
ERROR: aws_mxnet_cu101mkl-1.6.0rc0-py2.py3-none-manylinux1_x86_64.whl is not a supported wheel on this platform.
```
This issues requires the pip version to be downgraded and pinned to 19.3.1
=> Downgrade pip version and unpin awscli

README.rst
The README file has the following command to setup the sagemaker-mxnet-container repository:
```
cp dist/sagemaker-mxnet-container-*.tar.gz docker/1.6.0/.
```
The name of the tar file should be sagemaker_mxnet_container*.tar.gz and should be copied to the location docker/1.6.0/sagemaker_mxnet_container.tar.gz
This PR makes a documentation change to fix the error
=> Misspelling of sagemaker_mxnet_container_*.tar.gz

docker/1.6.0/py3/Dockerfile.cpu, docker/1.6.0/py3/Dockerfile.gpu
Use GluonNLP stable release tag.
Previously a pre-release commit was used.
=> Use GluonNLP stable release tag

docker/1.6.0/py2/Dockerfile.cpu, docker/1.6.0/py2/Dockerfile.gpu
Fix issue in installation of `sagemaker-containers` by constraining the version of `inotify-simple` being used in py2 dockerfiles to `inotify-simple<1.3`.
The following is the sequence of dependencies that causes this issue:
sagemaker-mxnet-training > sagemaker-containers > gevent > inotify-simple > enum34
Installation of `inotify-simple==1.3.0` results in the following error:
```
Collecting inotify-simple
Downloading https://files.pythonhosted.org/packages/d5/b9/e8893eb0cf4ea05f091ca833d4129c5cbb193535fd4962fb5bb23c54b79f/inotify_simple-1.3.0.tar.gz
ERROR: Command errored out with exit status 1:
command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-myOcJF/inotify-simple/setup.py'"'"'; …
```
=> fix: Fix issue in installation of sagemaker-containers

setup.py
sagemaker-containers==2.8.2 contains https://github.com/aws/sagemaker-containers/pull/261, which has a fix for requirements.txt support.
=> fix: upgrade sagemaker-containers to 2.8.2

docker/1.6.0/py2/Dockerfile.cpu, docker/1.6.0/py2/Dockerfile.gpu, docker/1.6.0/py3/Dockerfile.cpu, docker/1.6.0/py3/Dockerfile.gpu
This matches the other framework's Dockerfiles where the version is an upper bound rather than a specific version. Also, this should pick up the changes with aws/sagemaker-containers#261 (via #159)
=> change: use sagemaker_mxnet_training<4 in Dockerfiles instead of pinning the version

docker/1.6.0/py2/Dockerfile.cpu, docker/1.6.0/py2/Dockerfile.gpu, docker/1.6.0/py3/Dockerfile.cpu, docker/1.6.0/py3/Dockerfile.gpu
Safety issue
```
-> pillow, installed 6.2.0, affected <6.2.2, id 37782
libImaging/FliDecode.c in Pillow before 6.2.2 has an FLI buffer overflow. See: CVE-2020-5313.
--
-> pillow, installed 6.2.0, affected <6.2.2, id 37781
libImaging/PcxDecode.c in Pillow before 6.2.2 has a PCX P mode buffer overflow. See:CVE-2020-5312.
--
-> pillow, installed 6.2.0, affected <6.2.2, id 37780
libImaging/SgiRleDecode.c in Pillow before 6.2.2 has an SGI buffer overflow. See: CVE-2020-5311.
--
-> pillow, installed 6.2.0, affected <6.2.2, id 37779
libImaging/TiffDecode.c in Pillow before 6.2.2 has a TIFF decoding integer overflow, related to realloc. See: CVE-2020-5310.
--
-> pillow, installed 6.2.0, affected >6.0,<6.2.2, id 37772
There is a DoS vulnerability in Pillow before 6.2.2 …
```
=> upgrade pillow etc. to fix safety issues in 1.6.0 dockerfiles

setup.py, src/sagemaker_mxnet_container/training.py, test-toolkit/unit/test_training.py, test/unit/test_training.py
This PR replaces the deprecated [sagemaker-containers](https://github.com/aws/sagemaker-containers) package with the new [sagemaker-training](https://github.com/aws/sagemaker-training-toolkit) package.
=> breaking: Replace sagemaker-containers with sagemaker-training

.coveragerc_py37, buildspec-release.yml, buildspec-toolkit.yml, setup.py, tox.ini
- Upgrade version of sagemaker_training to `3.5.0`, which supports Python 3.7.
- Update tox and buildspecs to test against py37.
- Update Python version in `setup.py`.
=> feature: add Python 3.7 support

test/container/1.6.0/Dockerfile.dlc.cpu, test/container/1.6.0/Dockerfile.dlc.gpu
Since DLC released with OpenSSH I am removing this addition as it's redundant now
Related comment: https://github.com/aws/sagemaker-mxnet-training-toolkit/pull/178/files#r441667892
=> infra: Remove the openssh commands from dockerfile
